### ISSUE TITLE
Allow use of full duplex version.

### ISSUE THREAD

**Issue by NodeGuy** [psirenny/node-google-speech-api#1]
The new API version allows for longer clips.  See http://mikepultz.com/2013/07/google-speech-api-full-duplex-php-version/.

**Comment by psirenny** [comment]
I tried implementing and decided against going with the duplex API for the following reasons which... I should have posted a lot sooner:

1. They released v2 of their API shortly after. I worried they would deprecate the v1 duplex API in addition to the normal v1 API. Although, I don't think have.
2. The duplex API stops responding after a very short period of time.
3. The API responses really start to balloon in size because they return the entire transcript rather than the transcript for the streamed chunks only. Undoubtedly, this is done to recalculate and improve the accuracy of the original transcription. I just don't think it's really worth it.

For now, I've opted to stream chunks of the audio to the v2 api and stitch the responses back together.
